version: "3.1"

services:
  database:
    image: mariadb:jammy
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ASdf123$
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
